# Workflow name
name: data-pipeline-workflow

# Schedules for running
on:
    # push: # uncomment to run on push
    schedule:
      - cron: "35 0 * * *" # run every day at 12:35AM
    workflow_dispatch:

# Define the workflow itself
jobs:
    run-data-pipeline:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout repo content
             uses: actions/checkout@v4
             with:
                token: ${{ secrets.PAT_SECRET }}
           - name: Setup Python
             uses: actions/setup-python@v5
             with:
                python-version: '3.9'
                cache: 'pip'
           - name: Install dependancies
             run: pip install -r requirements.txt
           - name: Run data pipeline
             env:
                YT_API_KEY: ${{ secrets.YT_API_KEY }}
             run: python data_pipeline.py #runs the data pipeline
           - name: Check for changes
             id: git-check
             run: |
                 git config user.name 'github-actions'
                 git config user.email 'github-actions@github.com'
                 git add .
                 git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV 
           - name: Commit and push if changes
             if: env.changes == 'true' # if changes made push new data to repo
             run: |
               git commit -m "updated video index"
               git push


